pull required Docker images in Debian post-install script
introduce Docker image to run `tshark` tool

diff --git a/debian/template/DEBIAN/postinst b/debian/template/DEBIAN/postinst
--- a/debian/template/DEBIAN/postinst
+++ b/debian/template/DEBIAN/postinst
@@ -38,6 +38,14 @@ chmod 0755 -f /ryftone/.rest-*
 chown "$target_uid:$target_gid" -f -R /ryftone/.rest-*
 chown "$target_uid:$target_gid" -f /var/log/ryft/server.log
 
+# pull the Docker images (check the docker.images configuration options)
+[ -z "$RYFT_DO_NOT_PULL_DOCKER_IMAGES" ] && \
+(( docker pull alpine:latest \
+&& docker pull ubuntu:16.04 \
+&& docker pull python:2.7 \
+&& docker build -t ryft/alpine-tshark /usr/share/ryft/docker/tshark ) \
+|| echo "failed to pull some Docker images, the /run endpoint may fail" )
+
 echo $NAME starting...
 if [ -z `which systemctl` ]; then
 	# yes upstart
